# Generated by Django 4.2.7 on 2025-11-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='template_previews/'),
        ),
    ]
