# Generated by Django 4.2.7 on 2025-11-23 04:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_template_preview_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generationjob',
            options={},
        ),
        migrations.AlterModelOptions(
            name='imageasset',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveField(
            model_name='generationjob',
            name='result',
        ),
        migrations.RemoveField(
            model_name='imageasset',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='template',
            name='description',
        ),
        migrations.RemoveField(
            model_name='template',
            name='preview_image',
        ),
        migrations.AddField(
            model_name='generationjob',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imageasset',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='placeholder.png', upload_to='products/originals/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='generationjob',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='image',
            field=models.ImageField(upload_to='assets/'),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='kind',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='products.product'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='name',
            field=models.CharField(default='Default Logo', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='templates/backgrounds/'),
        ),
        migrations.AlterField(
            model_name='template',
            name='kind',
            field=models.CharField(default='social', max_length=50),
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='template',
            name='spec',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='generated/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_images', to='products.generationjob')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_images', to='products.product')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.template')),
            ],
        ),
    ]
